
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='grafiti',
    version='0.1.0',
    description='Automatic graph-based dependency resolution',
    python_requires='==3.*,>=3.6.0',
    author='Shiv Dhar',
    author_email='shiv.dhar@gmail.com',
    license='GPL-3.0-only',
    packages=['grafiti'],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
)
